AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  UrsHostname:
    Type: String
    AllowedValues:
    - https://urs.earthdata.nasa.gov
    - https://uat.urs.earthdata.nasa.gov
    Default: https://urs.earthdata.nasa.gov

  UrsTokenUri:
    Type: String
    Default: /oauth/token

  UrsClientId:
    Type: String

  UrsClientPassword:
    Type: String
    NoEcho: true

  UrsRedirectUri:
    Type: String

  CookieDomain:
    Type: String
    Default: .asf.alaska.edu

  CookieDurationInSeconds:
    Type: Number
    MinValue: 0
    Default: 86400

  PrivateKey:
    Type: String
    NoEcho: true

Outputs:

  LambdaArn:
    Value: !GetAtt Lambda.Arn

Resources:

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Name}-dlq"
      MessageRetentionPeriod: 1209600

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Name}"
      RetentionInDays: 30

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Name
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !GetAtt LogGroup.Arn
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt DeadLetterQueue.Arn

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref Name
      Code: src/
      DeadLetterConfig:
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Environment:
        Variables:
          URS_HOSTNAME: !Ref UrsHostname
          URS_TOKEN_URI: !Ref UrsTokenUri
          URS_CLIENT_ID: !Ref UrsClientId
          URS_CLIENT_PASSWORD: !Ref UrsClientPassword
          URS_REDIRECT_URI: !Ref UrsRedirectUri
          COOKIE_DOMAIN: !Ref CookieDomain
          COOKIE_DURATION_IN_SECONDS: !Ref CookieDurationInSeconds
          PRIVATE_KEY: !Ref PrivateKey
      Handler: main.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python3.7
      Timeout: 30
